import { execFile } from 'node:child_process';
import { access, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { Effect, Option, Schema } from 'effect';
import {
  CommandFailed,
  OxlintNotFound,
  ScratchWriteFailed,
  UnreadableOutput,
  describeCause,
} from './errors.ts';

/** Prefix every metric message carries, so the harness can pick its rows out. */
const PARITY_MARKER = '@@parity';

/** Name the harness registers its generated plugin under in the run config. */
const PARITY_PLUGIN = 'better-antislop-parity';

/** Name the plugin under test publishes, per `src/index.ts`. */
const METRICS_PLUGIN = 'better-antislop-metrics';

/**
 * The config sits next to `src/index.ts` so `./src/index.ts` resolves the same
 * way it does for `oxlint.config.ts`. It is removed when the run ends.
 */
const CONFIG_NAME = '.parity-oxlintrc.json';

const PLUGIN_DIR_PREFIX = 'better-antislop-parity';
const PLUGIN_NAME = 'plugin.ts';

const MAX_BUFFER = 256 * 1024 * 1024;
const SAMPLE_BYTES = 400;

/** One function as this plugin scored it, read back out of a diagnostic. */
export interface PluginRow {
  readonly file: string;
  readonly line: number;
  readonly name: string;
  readonly cognitive: number;
  readonly cyclomatic: number;
  readonly nesting: number;
}

export interface CollectResult {
  readonly rows: ReadonlyArray<PluginRow>;
  readonly filesLinted: number;
  /** Diagnostics from the plugin's own metric rules. Proof the rules ran. */
  readonly ruleDiagnostics: number;
  /** Metric diagnostics that carried no label, so they cannot be keyed. */
  readonly unlabelledDiagnostics: number;
  /**
   * Files oxlint refused to parse, so the plugin never saw a function in them.
   *
   * A parse error yields no metric rows at all, which would otherwise resurface
   * downstream as one `leadline-only` row per function and read like a scoring
   * dispute. Reported by name so the corpus problem is visible as such.
   */
  readonly unparsedFiles: ReadonlyArray<UnparsedFile>;
}

/** One file oxlint could not parse, with the reason it gave. */
export interface UnparsedFile {
  readonly file: string;
  readonly detail: string;
}

const Diagnostic = Schema.Struct({
  message: Schema.String,
  // Optional because a parser error carries no `code`, and requiring it would
  // abort the whole run on the first unparseable file. `code` is load-bearing:
  // `isParseError` reads it to tell a broken file from a finding.
  code: Schema.optionalKey(Schema.String),
  filename: Schema.String,
  labels: Schema.Array(Schema.Struct({ span: Schema.Struct({ line: Schema.Int }) })),
});

const OxlintOutput = Schema.Struct({
  diagnostics: Schema.Array(Diagnostic),
  number_of_files: Schema.optionalKey(Schema.Int),
});
type OxlintDiagnostic = Schema.Schema.Type<typeof Diagnostic>;
type OxlintReport = Schema.Schema.Type<typeof OxlintOutput>;

const decodeOxlintOutput = Schema.decodeEffect(Schema.fromJsonString(OxlintOutput));

const PARITY_MESSAGE = /^@@parity cognitive=(-?\d+) cyclomatic=(-?\d+) nesting=(-?\d+) name=(.*)$/;

interface ParityFields {
  readonly cognitive: number;
  readonly cyclomatic: number;
  readonly nesting: number;
  readonly name: string;
}

/** Parses one `@@parity` message, or reports that it is not one. */
function parseParityMessage(message: string): ParityFields | null {
  const match = PARITY_MESSAGE.exec(message);
  if (match === null) {
    return null;
  }
  const [, cognitive, cyclomatic, nesting, name] = match;
  if (
    cognitive === undefined ||
    cyclomatic === undefined ||
    nesting === undefined ||
    name === undefined
  ) {
    return null;
  }
  return {
    cognitive: Number.parseInt(cognitive, 10),
    cyclomatic: Number.parseInt(cyclomatic, 10),
    nesting: Number.parseInt(nesting, 10),
    name,
  };
}

/**
 * The plugin reports its own rule findings, so the run needs a rule that emits
 * one diagnostic per function instead. This generated plugin calls the same
 * `analyzeProgram` the real rules call, so the numbers compared are the numbers
 * the rules would see.
 */
function pluginSource(enginePath: string): string {
  return `// Generated by tools/parity. Removed when the run ends.
import type { Context, ESTree } from '@oxlint/plugins';
import { analyzeProgram } from ${JSON.stringify(enginePath)};

const MARKER = ${JSON.stringify(PARITY_MARKER)};

export default {
  meta: { name: ${JSON.stringify(PARITY_PLUGIN)} },
  rules: {
    parity: {
      create(context: Context) {
        return {
          Program(node: ESTree.Program): void {
            const metrics = analyzeProgram(node, { filename: context.filename });
            for (const fn of metrics.functions) {
              context.report({
                loc: { start: fn.span.start, end: fn.span.end },
                message:
                  MARKER +
                  ' cognitive=' + fn.cognitive +
                  ' cyclomatic=' + fn.cyclomatic +
                  ' nesting=' + fn.maxNesting +
                  ' name=' + (fn.name === null ? '' : fn.name),
              });
            }
          },
        };
      },
    },
  },
};
`;
}

/** The plugin under test with its three metric rules enabled. */
function configSource(pluginPath: string): string {
  return `${JSON.stringify(
    {
      jsPlugins: [
        { name: METRICS_PLUGIN, specifier: './src/index.ts' },
        { name: PARITY_PLUGIN, specifier: pluginPath },
      ],
      rules: {
        [`${METRICS_PLUGIN}/cognitive-complexity`]: 'error',
        [`${METRICS_PLUGIN}/max-nesting-depth`]: 'error',
        [`${METRICS_PLUGIN}/min-maintainability-index`]: 'error',
        [`${PARITY_PLUGIN}/parity`]: 'error',
      },
    },
    null,
    2,
  )}\n`;
}

function writeFileAt(path: string, contents: string): Effect.Effect<void, ScratchWriteFailed> {
  return Effect.tryPromise({
    try: () =>
      mkdir(dirname(path), { recursive: true }).then(() => writeFile(path, contents, 'utf8')),
    catch: (cause) => new ScratchWriteFailed({ path, detail: describeCause(cause) }),
  });
}

function writeScratch(
  configPath: string,
  pluginPath: string,
  enginePath: string,
): Effect.Effect<void, ScratchWriteFailed> {
  return Effect.gen(function* () {
    yield* writeFileAt(pluginPath, pluginSource(enginePath));
    yield* writeFileAt(configPath, configSource(pluginPath));
  });
}

/** Deletes the scratch files, and says so when one of them survives. */
function removeScratch(paths: ReadonlyArray<string>): Effect.Effect<void> {
  return Effect.gen(function* () {
    for (const path of paths) {
      const removed = yield* Effect.option(
        Effect.tryPromise(() => rm(path, { recursive: true, force: true })),
      );
      if (Option.isNone(removed)) {
        yield* Effect.sync(() => {
          process.stderr.write(`parity: could not remove scratch path ${path}\n`);
        });
      }
    }
  });
}

interface Captured {
  readonly exitCode: number | string | null;
  readonly stdout: string;
  readonly stderr: string;
}

/**
 * Starts `oxlint` and always resolves.
 *
 * The exit code of the child is data here, not an exception, so it survives to
 * the caller. `Effect.tryPromise` then only has to cover a spawn that throws.
 */
function capture(binary: string, args: ReadonlyArray<string>, cwd: string): Promise<Captured> {
  const { promise, resolve } = Promise.withResolvers<Captured>();
  execFile(binary, [...args], { cwd, maxBuffer: MAX_BUFFER }, (error, stdout, stderr) => {
    resolve({ exitCode: error === null ? 0 : (error.code ?? null), stdout, stderr });
  });
  return promise;
}

/** Fails when the binary is not on disk, so the caller never spawns nothing. */
function assertBinaryPresent(binary: string): Effect.Effect<void, OxlintNotFound> {
  return Effect.gen(function* () {
    const reachable = yield* Effect.option(Effect.tryPromise(() => access(binary)));
    if (Option.isNone(reachable)) {
      return yield* Effect.fail(
        new OxlintNotFound({ binary, detail: 'run `bun install` in the package root' }),
      );
    }
  });
}

/** The child's stdout, or a failure carrying whatever the child explained. */
function readCaptured(captured: Captured, command: string): Effect.Effect<string, CommandFailed> {
  return Effect.gen(function* () {
    if (captured.exitCode !== 0 && captured.exitCode !== 1) {
      return yield* Effect.fail(
        new CommandFailed({
          tool: 'oxlint',
          exitCode: captured.exitCode,
          command,
          detail: captured.stderr.length > 0 ? captured.stderr : captured.stdout,
        }),
      );
    }
    return captured.stdout;
  });
}

/**
 * Runs `oxlint` over `target` with the generated config and returns stdout.
 *
 * Exit code 1 means lint findings, which this run always produces, so only a
 * code outside `0` and `1` is a failure.
 */
function runOxlint(
  target: string,
  packageRoot: string,
  configPath: string,
): Effect.Effect<string, OxlintNotFound | CommandFailed> {
  const binary = join(packageRoot, 'node_modules', '.bin', 'oxlint');
  const args = ['--config', configPath, '--format', 'json', target];
  const command = `oxlint ${args.join(' ')}`;
  return Effect.gen(function* () {
    yield* assertBinaryPresent(binary);
    const captured = yield* Effect.tryPromise({
      try: () => capture(binary, args, packageRoot),
      catch: (cause) =>
        new CommandFailed({
          tool: 'oxlint',
          exitCode: null,
          command,
          detail: describeCause(cause),
        }),
    });
    return yield* readCaptured(captured, command);
  });
}

function readOxlintOutput(stdout: string): Effect.Effect<OxlintReport, UnreadableOutput> {
  return Effect.mapError(
    decodeOxlintOutput(stdout),
    (error) =>
      new UnreadableOutput({
        tool: 'oxlint',
        detail: error.message,
        sample: stdout.slice(0, SAMPLE_BYTES),
      }),
  );
}

type Extraction = Omit<CollectResult, 'filesLinted'>;

/**
 * A diagnostic with no `code` is a parse error, not a lint finding.
 *
 * Every rule diagnostic names its rule, including oxlint's built-in ones and
 * this plugin's own, so a codeless diagnostic is one oxlint never got to
 * score. Verified against oxlint 1.87.0 rather than assumed.
 *
 * Do not add a second condition here for robustness. A parse error often does
 * carry a label pointing at the offending token, so anything keying on labels
 * would misclassify it as a finding and hide the file again. `code` is the
 * only signal checked to be reliable.
 */
function isParseError(diagnostic: OxlintDiagnostic): boolean {
  return diagnostic.code === undefined;
}

/** Splits the run's diagnostics into metric rows, findings and parse errors. */
function extractRows(diagnostics: ReadonlyArray<OxlintDiagnostic>): Extraction {
  const rows: PluginRow[] = [];
  const unparsedFiles: UnparsedFile[] = [];
  let ruleDiagnostics = 0;
  let unlabelledDiagnostics = 0;
  for (const diagnostic of diagnostics) {
    const fields = parseParityMessage(diagnostic.message);
    if (fields === null) {
      if (isParseError(diagnostic)) {
        unparsedFiles.push({ file: diagnostic.filename, detail: diagnostic.message });
      } else {
        ruleDiagnostics += 1;
      }
      continue;
    }
    const label = diagnostic.labels[0];
    if (label === undefined) {
      unlabelledDiagnostics += 1;
      continue;
    }
    rows.push({ file: diagnostic.filename, line: label.span.line, ...fields });
  }
  return { rows, ruleDiagnostics, unlabelledDiagnostics, unparsedFiles };
}

/**
 * Runs `oxlint` over `target` under a generated config and returns the rows the
 * plugin reported, one per function.
 *
 * `target` is absolute. `packageRoot` anchors both the config and the working
 * directory of the child, never the process working directory.
 */
export function collectPluginMetrics(
  target: string,
  packageRoot: string,
): Effect.Effect<
  CollectResult,
  OxlintNotFound | CommandFailed | UnreadableOutput | ScratchWriteFailed
> {
  const configPath = join(packageRoot, CONFIG_NAME);
  const pluginDir = join(tmpdir(), `${PLUGIN_DIR_PREFIX}-${process.pid}`);
  const pluginPath = join(pluginDir, PLUGIN_NAME);
  // Point at the implementation rather than the seam. `contract.ts` re-exports
  // `analyzeProgram`, so both paths resolve today, but `analyze.ts` is the code
  // that actually runs and cannot drift if the seam is ever reorganised.
  const enginePath = join(packageRoot, 'src', 'engine', 'analyze.ts');
  const program = Effect.gen(function* () {
    yield* writeScratch(configPath, pluginPath, enginePath);
    const stdout = yield* runOxlint(target, packageRoot, configPath);
    const report = yield* readOxlintOutput(stdout);
    return { filesLinted: report.number_of_files ?? 0, ...extractRows(report.diagnostics) };
  });
  return Effect.ensuring(program, removeScratch([configPath, pluginDir]));
}
